auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Sanplt--
url: http://sanplit.github.io/
feed: /atom.xml
author_info: <a href="http://sanplit.github.io/">Sanplt</a>
